
apiVersion: v1
kind: List
metadata:
items:  
- apiVersion: v1
  kind: Secret
  metadata:
    name: sambaauth
  type: kubernetes.io/basic-auth
  stringData:
    share: Share01
    server: 40.85.160.196
    username: SMB-USER
    password: Aa123456 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: collector
    name: collector-dhcp-file
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: collector
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: collector
      spec:
        containers:
        - env:
          - name: LOGFILE
            value: "DhcpSrvLog-Mon.log"
          - name: KAFKA_HOSTS
            value: kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092
          image: quay.io/ypery/srm-dhcp:v0.12
          imagePullPolicy: Always
          name: collector-dhcp-file
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: sambaauth
            mountPath: "/sambaauth"
            readOnly: true
        volumes:
        - name: sambaauth
          secret:
            secretName: sambaauth
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

